language: python
python:
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
env:
    - DJANGO_VERSION=1.8.14
    - DJANGO_VERSION=1.9.9
    - DJANGO_VERSION=1.10
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.9.9
    - python: "3.3"
      env: DJANGO_VERSION=1.10
before_install:
    - export DJANGO_SETTINGS_MODULE="pygmentify.tests.settings"
install:
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install
script:
    - django-admin.py test pygmentify.tests