language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
env:
    - DJANGO_VERSION=1.8.18
    - DJANGO_VERSION=1.9.13
    - DJANGO_VERSION=1.10.7
    - DJANGO_VERSION=1.11
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO_VERSION=1.8.18
    - python: "3.3"
      env: DJANGO_VERSION=1.9.13
    - python: "3.6"
      env: DJANGO_VERSION=1.9.13
    - python: "3.3"
      env: DJANGO_VERSION=1.10.7
    - python: "3.6"
      env: DJANGO_VERSION=1.10.7
    - python: "3.3"
      env: DJANGO_VERSION=1.11
before_install:
    - export DJANGO_SETTINGS_MODULE="pygmentify.tests.settings"
install:
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install
script:
    - django-admin test pygmentify.tests